### ISSUE TITLE
4k HEVC ok, but HDR makes the MacBook Air fan spin up

### ISSUE THREAD

**Issue by bondskin** [AerialScreensaver/Aerial#17]
All,

not sure if this is considered a bug.
My config:
MacBook Air (Retina, 13 Zoll, 2020)
Processor: 1,2 GHz Quad-Core Intel Core i7
Memory: 8 GB 3733 MHz LPDDR4X

Using HEVC videos does not let my fan start while videos are being played.
Choosing the 4k HDR option makes the fan to start.

Is this known or any chance to prevent this?

thx

**Comment by glouel** [comment]
Hey @bondskin 

The HDR videos are encoded thru Dolby Vision by Apple, and that decoding is pretty taxing on the GPU (which is not great on Intel) so that makes the fan spins. You can double check by opening a HDR video from Aerial's cache in Quicktime, you should see the same results. 

So not much I can do about that one sorry, I'd recommend running HDR off on pre Apple Silicon MacBook Airs.

**Comment by bondskin** [comment]
thank you for your swift reply, much appreciated.
And Thank You for your great work!
