### ISSUE TITLE
Aerial Updater crashes during update (in trust evaluation)

### ISSUE THREAD

**Issue by taw123** [AerialScreensaver/Aerial#18]
Attached at the crash report and corresponding console messages (filtered for Aerial).

Seems so be failing with at an OS level with a security error **UNIX error exception: 17** which is resulting in a the updater crashing with a Termination Signal:    **Illegal instruction: 4** Termination Reason:    Namespace SIGNAL, Code 0x4  Terminating Process:   exc handler [22322].

I have repeatedly downloaded the the binary from GitHub [https://github.com/glouel/AerialCompanion/releases/latest/download/AerialInstaller.dmg](GitHub) so I know there's no issue with the actual integrity of the app, and SEEMS to be rather with the download/update. Current version of Aerial is 2.1, companion download is current (v1.1).

Environment: **Mac OS 10.15.7 (19H15)**,  MacBook Pro (15-inch, 2017)

Let me know if any other files or data would be helpful. I am a former Apple Engineer and have access to Apps/Dev Enviorment.

Thanks,
Tom
[Aerial Updater crash (console log).txt](https://github.com/glouel/AerialCompanion/files/5600213/Aerial.Updater.crash.console.log.txt)

[Aerial_2020-11-25-183708_Laptop.crash.txt](https://github.com/glouel/AerialCompanion/files/5600217/Aerial_2020-11-25-183708_Laptop.crash.txt)

**Comment by ZV00** [comment]
Just going to tag @glouel To make sure he sees this one.

**Comment by glouel** [comment]
Hey Tom ! 

Sorry about that and thanks for the report. Can you look in ~/Library/Application Support/AerialUpdater/ for a Log.txt file ? This may give me a clue.

Just to get more context, did you have a version of Aerial (the screensaver) installed already ? And this happened when you were notified of an update ? Or is this a fresh install when this happened when launching the companion (and it crashed while installing for you). What exact version also fo you have of Aerial installed if any ? Latest is 2.1.5 so that's likely what companion downloaded for you. 

At first glance it may have failed to launch some command after the download, like unzip to extract the downloaded file. A bit weird but maybe. 

I'll think about it and get back to you asap.
