### ISSUE TITLE
Prior Aerial Companion menu options missing after update to v1.4.0beta1

### ISSUE THREAD

**Issue by Pcar17** [AerialScreensaver/Aerial#34]
Hi,

I just installed v1.4.0beta1 of Aerial Companion (along with Aerial Release v3.0.5).  I'm not seeing the original Aerial Companion menu options available from the menu bar anymore like [here](https://user-images.githubusercontent.com/18543749/90840214-65d66300-e327-11ea-937c-6885f1ff1b4c.png) that's been around for awhile now.  Is the old Aerial Companion UI gone? Note that I am using Aerial on an M1 MBA with the latest MacOS 12.3 Beta (21E5196i) installed. 

Here is what I see when clicking on the Aerial Companion menu item:

<img width="804" alt="Screen Shot 2022-02-07 at 4 29 30 PM" src="https://user-images.githubusercontent.com/44177062/152883268-d1d2b0a3-1c48-4e1d-8ae4-21efe42584d3.png">

Update.....I just found the sub-UI menu! My bad! 
But what about putting back the prior "Check Now" dialogue? 

<img width="510" alt="Screen Shot 2022-02-07 at 5 16 32 PM" src="https://user-images.githubusercontent.com/44177062/152888474-5e241cb2-0714-477f-8dfc-66f8ebb92381.png">

**Comment by glouel** [comment]
Hey @Pcar17 !

So yep I'm trying this new UI because the menu was too cramped and hard to make dynamic. One cool thing with the new one is that I can dynamically change it, so for example in wallpaper mode it looks like this :

![Capture_decran_2022-02-06_a_23 32 00](https://user-images.githubusercontent.com/37544189/153058657-22672799-c4fd-4547-b986-dbf391314566.png)

And I've added some new features like stopping, pausing, skipping and hiding a video. 

Now  as you've acurately noted, I missed a couple of features in that beta  🙈 Check now is no longer there and I'll add it back. Also, you can't check/uncheck debug mode but that's about it.

I'm still working on that UI but I think it will look a lot better in the long run than the old menu. Let me know if you have any feedback on it.

**Comment by Pcar17** [comment]
Thanks @glouel for the update! Sounds like a good plan.  

I'll of course let you know if I have anything to add when you release your next beta.

Btw, everything is very stable right now on my M1 MBA.  Also, I am downloading today's new Monterey beta right now.

**Comment by Pcar17** [comment]
Hi,
Quick update....I just reverted back to the last production release, 1.2.2. It's UI is working much better functionally for me than the latest beta version--I really have missed it.  :-)

**Comment by glouel** [comment]
Hey @Pcar17 

Is it just the check now button or are there other things ? I haven't had time to work more on this but any feedback is good, thanks !

**Comment by Pcar17** [comment]
> Hey @Pcar17
> 
> Is it just the check now button or are there other things ? I haven't had time to work more on this but any feedback is good, thanks !

Hi @glouel,
I’m away from my laptop through later this week….will update then as I want to check.
Thx! Pcar17

**Comment by Pcar17** [comment]
2glouel, 

The main thing is to just not lose v1.2.2 functionality in the new current drop-down.  Also, the 1.2.2 drop-down is just so easy to use....not that your new features in v1.4.0 are not valuable though! Thx!

<img width="300" alt="Screen Shot 2022-04-06 at 4 16 25 PM" src="https://user-images.githubusercontent.com/44177062/162072555-a05007e9-07cb-40e0-a2d0-1e70466b1f01.png">
