### ISSUE TITLE
Respect disabled Aerial

### ISSUE THREAD

**Issue by fuzzy76** [AerialScreensaver/Aerial#35]
If I have selected another screen saver, Aerial Companion will change back to Aerial when updating. Please don't make me uninstall Aerial Companion just because I want to try other screen savers. :)

**Comment by glouel** [comment]
Hey @fuzzy76 

Indeed, as part of the initial install companion does set Aerial as default, that's what I intended. A side effect of this, because it's using the same code, is that it also sets itself again on update, which is definitely a bit hostile.

I'll have a look at fixing this for next beta, thanks for the report.

**Comment by glouel** [comment]
Hey @fuzzy76 

It's been a while but this is finally fixed in upcoming version of Companion, I removed the hostile bit and there's a button to set it as default in the menu now.

![Capture d’écran 2023-05-15 à 18 56 41](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/d2744449-d147-48ce-97fd-a62c9acd45b0)

This will be released later this week.
