### ISSUE TITLE
Unable to open settings

### ISSUE THREAD

**Issue by dhawan1997** [AerialScreensaver/Aerial#55]
Hi there; been a massive fan of the app for a while. I only noticed today that the settings of this app don't open. Whether I try it from the Menu bar icon→ Open Settings. Or go to System Preferences → Wallpaper→ Options.

I wanted to ask you if running the beta will fix this.

Currently, I am on an M1 MBP 14in—no external displays. Aerial Companion, 1.2.2 with the '3.2.3, is installed' message.

Request your kind help and guidance, please.

**Comment by glouel** [comment]
Hey @dhawan1997 

To answer your question, yes, Companion 1.2.2 won't open settings from its menu on Ventura, because of the changes with System Preferences.

System Preferences -> Screen Saver -> Options works "most of the time" but fails some of the time, for some reason, the bug is on Apple side... (one more !)

Long story short, Companion beta will 100% open settings, get it here :  https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

**Comment by dhawan1997** [comment]
Hey @glouel Thank you for your kind and prompt response. I just downloaded the beta for the first time. Will try it out.

**Comment by glouel** [comment]
Awesome, let me know if you hit any issues. Also make sure to follow those steps to get rid of the notifications when your mac starts : https://github.com/AerialScreensaver/AerialCompanion/issues/51#issuecomment-1397265056
