### ISSUE TITLE
Just info request: difference in actual display between HEIC and HDR files?

### ISSUE THREAD

**Issue by hstriepe** [AerialScreensaver/Aerial#62]
I see the two options in Settings. What is the actual display difference between HEIC and HDR file formats?

**Comment by glouel** [comment]
@hstriepe HDR is High Dynamic Range, in short, very bright ! There should be an explanation when you click the ? button

![Capture d’écran 2023-06-23 à 18 52 14](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/b2346760-99e7-454a-8a40-c5365b3f8b47)

240 FPS which is in the latest beta is, as the name implies, videos with 240 frames per second (instead of 24).
