### ISSUE TITLE
1.5.0b9 marked as "Latest Release" on purpose?

### ISSUE THREAD

**Issue by core-code** [AerialScreensaver/Aerial#64]
is this still a beta or a stable release? has it been marked as "Latest Release" in github on purpose? should we use 1.2.2 of 1.5.0b9?

thanks!

**Comment by glouel** [comment]
Great question, I guess it's a bit of both, I hesitated a couple of times. The current stable (1.2.2) is so outdated that I think it's much preferable people use the new one, so many things are broken now in latest macOS versions, which is why I went with latest release. 

I highly recommend you give it a shot, it's likely I will make it 1.5.0 finale barring any last minute bug.

**Comment by core-code** [comment]
thanks for the confirmation here!
