### ISSUE TITLE
Random sequence and stuttering 4K videos

### ISSUE THREAD

**Issue by ghost** [AerialScreensaver/Aerial#9]
Hi Guillaume,

really like your new companion app - works well, easy to use and looks good! Using the latest 2.0.2 and also downloaded / cached my favourite rotation (~37 videos in 4K HEVC format). However, I noticed a couple of things

- I often keep seeing the same handful of videos when the screensaver starts. Could there be an issue with the random generator? 
- I chose 4K HEVC which looks great on my big 4K TV, but seems to challenge my late 2014 Mac mini (with SSD). Some videos play smoothly (!), whereas others stutter along, even though I've downloaded my rotation. Any suggestions?

Cheers
Eric

**Comment by ZV00** [comment]
Hey Eric!

Regarding your first question:
This FAQ may help answer your questions regarding the limited rotation: https://github.com/JohnCoates/Aerial/blob/master/Documentation/FAQs.md#videos-not-playing Specifically, check your on rotation and location settings. 

As for the second question, this may be due to caching in the background. Can you check to see if you have automatic caching enabled? If so, that may be causing the lag. You can get around this by filling your cache first and then manually rotating it if it bothers you.

**Comment by ghost** [comment]
Many thanks!! I turned off automatic download and just downloaded my rotation (eg Scene - Nature). It seems to mix it up better now.

On the stuttering: even after I downloaded the whole rotation, my (late 2014) Mac mini just doesn't seem able to process anything beyond 1080p H264 despite 8GB RAM and SSD, which is a pity. The 4K video obviously look sharper on my big screen, but I can't get them to run smoothly.

But great work - thanks so much for writing the companion app!!
